#!/bin/bash
# MAAD App Deployment Diagnostic

echo "🔍 MAAD App Deployment Diagnostic"
echo "=================================="

echo ""
echo "📍 Your live app should be at:"
echo "   https://peggy12.github.io/maad-app/"

echo ""
echo "🔧 Troubleshooting Steps:"
echo ""
echo "1. Check GitHub Actions:"
echo "   Go to: https://github.com/peggy12/maad-app/actions"
echo "   Look for: ✅ green checkmarks or ❌ red X marks"
echo ""
echo "2. Verify GitHub Pages is enabled:"
echo "   Go to: https://github.com/peggy12/maad-app/settings/pages"
echo "   Source should be: 'GitHub Actions'"
echo ""
echo "3. Check Environment Variables (Secrets):"
echo "   Go to: https://github.com/peggy12/maad-app/settings/secrets/actions"
echo "   You should have 5 secrets:"
echo "   - VITE_FACEBOOK_PAGE_ID"
echo "   - VITE_FACEBOOK_ACCESS_TOKEN"
echo "   - VITE_BASE44_BASE_URL"
echo "   - VITE_BASE44_AGENT_NAME"
echo "   - VITE_BASE44_API_KEY"
echo ""
echo "4. Check browser console for errors:"
echo "   Press F12 → Console tab → Look for red error messages"
echo ""
echo "5. Try force refresh:"
echo "   Press Ctrl+F5 (or Cmd+Shift+R on Mac)"

echo ""
echo "📱 What should work when live:"
echo "✅ Base44 chat widget at the top"
echo "✅ Facebook job search (type 'search facebook jobs')"
echo "✅ Mobile responsive design"
echo "✅ HTTPS security"

echo ""
echo "🆘 If still not working, tell me:"
echo "   - What error message do you see?"
echo "   - What happens when you visit the URL?"
echo "   - Are there any red X marks in GitHub Actions?"